In [26]:
import numpy as np
from PIL import Image

if __name__ == '__main__':
    image_file = './timg.jpg'
    height = 100
    
    img = Image.open(image_file)
    img_width, img_height = img.size
    width = 2 * height * img_width // img_height
    img = img.resize((width, height), Image.ANTIALIAS)  # img.resize() 改变图像尺寸（图像缩放）。
    pixels = np.array(img.convert('L'))
    print(pixels.shape)
    print(pixels)
    chars = 'MNHQ$OC?7>!:-;. '  # 字符串
    N = len(chars)
    step = 256 // N
    print(N)
    result = ''
    for i in range(height):
        for j in range(width):
            result += chars[pixels[i][j] // step]
        result += '\n'
        
    with open('./timg.txt', mode='w') as f:
        f.write(result)

(100, 180)
[[194 194 194 ... 194 194 195]
 [194 194 194 ... 194 194 195]
 [194 194 194 ... 194 194 195]
 ...
 [153 151 160 ... 194 194 195]
 [155 154 171 ... 194 194 195]
 [155 155 155 ... 194 194 195]]
16


In [19]:
import numpy as np
from PIL import Image

if __name__ == '__main__':
    img_file = './timg.jpg'
    
    img = Image.open(img_file)  # 生成图片对象
    img_L = img.convert(mode='L')  # 将图像转换为灰度图像 https://www.2cto.com/kf/201603/492898.html
#     img.save('./L.jpg')  # 保存图像，看一下灰度图是什么样子的
    pixels = np.array(img_L)  # 图像转换为数组
    
    print(pixels)
    print(pixels.min(), pixels.max())
    print(pixels.shape)
    print(img.height)
    print(img.width)
    
    chars = 'MNHQ$OC?7>!:-;. '  # 字符串
    step = 255 // len(chars)  # 划分几个区间
    result = ''
    for i in range(img.height):  # 将数组中的值变为对应的字符，好像 pandas 有这个功能，回头找一下......
        for j in range(img.width):
            result += chars[pixels[i][j] // step]  # 对应字符
        result += '\n'  # 每行最后换行
        
    with open('./timg.txt', mode='w') as f:  # 将结果写入文档
        f.write(result)

[[194 194 194 ... 193 194 198]
 [194 194 194 ... 193 194 198]
 [194 194 194 ... 193 194 198]
 ...
 [155 155 155 ... 193 194 198]
 [155 155 155 ... 193 194 198]
 [155 155 155 ... 193 194 198]]
0 255
(1200, 1080)
1200
1080


IndexError: string index out of range

In [25]:
pixels[1199][1079] // step
chars[13]

';'