In [15]:
import numpy as np
from PIL import Image

if __name__ == '__main__':
    image_file = './scc.jpg'
    height = 100
    
    img = Image.open(image_file)
    img_width, img_height = img.size
    width = 2 * height * img_width // img_height
    img = img.resize((width, height), Image.ANTIALIAS)  # img.resize() 改变图像尺寸（图像缩放）。
    pixels = np.array(img.convert('L'))
    print(pixels.shape)
    print(pixels)
    chars = 'MNHQ$OC?7>!:-;. '  # 字符串
    N = len(chars)
    step = 256 // N
    print(N)
    result = ''
    for i in range(height):
        for j in range(width):
            result += chars[pixels[i][j] // step]
        result += '\n'
        
    with open('./scc.txt', mode='w') as f:
        f.write(result)

(100, 133)
[[30 30 31 ... 30 28 27]
 [31 31 31 ... 31 30 29]
 [31 31 31 ... 31 31 30]
 ...
 [29 30 30 ... 25 24 23]
 [29 29 30 ... 24 23 22]
 [29 29 29 ... 23 23 22]]
16
